name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Build and run the Docker containers
      run: docker-compose up --build -d
    
    - name: Wait for containers to be healthy
      run: |
        # Give containers time to start up
        sleep 30
        
        # Check container status
        docker-compose ps
        
        # Show logs for debugging
        docker-compose logs
    
    - name: Run Django tests
      # Use -T flag to disable pseudo-TTY allocation
      run: docker-compose exec -T django-web python manage.py test
